# Opcode Exception

<!-- TOC -->

- [1. throw exception](#1-throw-exception)
- [2. catch exception](#2-catch-exception)
- [3. Summing-up](#3-summing-up)

<!-- /TOC -->

There is no bytecode instruction to catch exceptions: instead **the bytecode of a method** is associated with **a list of exception handlers** that specify the code that must be executed when an exception is thrown in a given part of a method. **An exception handler** is similar to a `try catch` block: it has a **range**, which is a sequence of instructions that corresponds to the content of the `try` block, and a **handler**, which corresponds to the content of the `catch` block. The **range** is specified by a `start` and `end` labels, and the **handler** with a `start` label.

- exception handler
  - range
    - start
    - end
  - handler
    - start

```txt
Code_attribute {
    u2 attribute_name_index;
    u4 attribute_length;
    u2 max_stack;
    u2 max_locals;
    u4 code_length;
    u1 code[code_length];
    u2 exception_table_length;
    {
        u2 start_pc;
        u2 end_pc;
        u2 handler_pc;
        u2 catch_type;
    } exception_table[exception_table_length];
    u2 attributes_count;
    attribute_info attributes[attributes_count];
}
```

## 1. throw exception

学习目标：

- `athrow`

示例代码：

```java
public class HelloWorld {
    public void testSimple() {
        throw new RuntimeException();
    }
}
```

输出结果：

```txt
ConstantPool {
    |002| CONSTANT_Class {Value='java/lang/RuntimeException', HexCode='070011'}
    |003| CONSTANT_Methodref {Value='java/lang/RuntimeException.<init>:()V', HexCode='0A00020010'}
    ......

code='BB000259B70003BF'
    0: new 2           // BB0002
    3: dup             // 59
    4: invokespecial 3 // B70003
    7: athrow          // BF


LocalVariableTable:
index  start_pc  length  name_and_type
    0         0       8  this:Llsieun/sample/HelloWorld;
```

## 2. catch exception

学习目标：

示例代码：

```java
public class HelloWorld {
    public void testSimple() {
        try {
            Thread.sleep(10);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```

输出结果：

```txt
ConstantPool {
    |002| CONSTANT_Long {Value='10', HexCode='05000000000000000A'}
    |004| CONSTANT_Methodref {Value='java/lang/Thread.sleep:(J)V', HexCode='0A00180019'}
    |005| CONSTANT_Class {Value='java/lang/InterruptedException', HexCode='07001A'}
    |006| CONSTANT_Methodref {Value='java/lang/InterruptedException.printStackTrace:()V', HexCode='0A0005001B'}
    ......

code='140002B80004A700084C2BB60006B1'
    0: ldc2_w 2        // 140002
    3: invokestatic 4  // B80004
    6: goto 8          // A70008
    9: astore_1        // 4C
   10: aload_1         // 2B
   11: invokevirtual 6 // B60006
   14: return          // B1

Exception table:
start_pc  end_pc  handler_pc  catch_type  Exception
       0       6           9           5  java.lang.InterruptedException

LocalVariableTable:
index  start_pc  length  name_and_type
    0         0      15  this:Llsieun/sample/HelloWorld;
    1        10       4  e:Ljava/lang/InterruptedException;
```

This means that if such **an exception** is thrown anywhere between `try` and `catch` the stack is cleared, **the exception** is pushed on this empty stack, and execution continues at `catch`.

## 3. Summing-up

知识整理
